variable,session: add search_path system variable.
DigitalChinaOpenSource/TiDB-for-PostgreSQL pull request #58
Opened 2021-09-03 07:18 UTC by Orion7r

### What problem does this PR solve?

Add a PostgreSQL system variable named "search_path".

### What is changed and how it works?

What's Changed:

Add a system variable,named 'search_path',default value is 'public'.

How it Works:

Now，we can run the related SQL statements properly，like ' set search_path to public'

2021-09-03 07:24 UTC, AmoebaProtozoa approved these changes
LGTM

2021-09-06 01:20 UTC, AmoebaProtozoa approved these changes
LGTM

2021-09-06 02:29 UTC, pupillord requested changes

2021-09-06 02:29 UTC, pupillord commented on infoschema/tables.go
> +// todo Table names in system tables need to be replaced with lower case
Here are two identical comments.

2021-09-06 03:34 UTC, Orion7r commented on infoschema/tables.go
> +// todo Table names in system tables need to be replaced with lower case
Next commit fix it.

2021-09-06 03:35 UTC, pupillord approved these changes
LGTM

2021-09-06 03:35 UTC, AmoebaProtozoa approved these changes
LGTM

2021-09-06 03:58 UTC, merged